const workoutOptions = [
  // Chest Exercises
  "Bench Press",
  "Incline Bench Press",
  "Decline Bench Press",
  "Dumbbell Bench Press",
  "Chest Fly",
  "Incline Chest Fly",
  "Decline Chest Fly",
  "Cable Crossover",
  "Push-Up",
  "Incline Push-Up",
  "Decline Push-Up",
  "Chest Dip",
  "Pec Deck Machine",
  "Svend Press",
  "Landmine Press",
  "Guillotine Press",
  "Plate Press",
  "Machine Chest Press",

  // Back Exercises
  "Deadlift",
  "Romanian Deadlift",
  "Stiff-Legged Deadlift",
  "Sumo Deadlift",
  "Bent-Over Row",
  "Yates Row",
  "Pendlay Row",
  "T-Bar Row",
  "Inverted Row",
  "Single-Arm Dumbbell Row",
  "Chest-Supported Row",
  "Seated Cable Row",
  "Wide-Grip Lat Pulldown",
  "Reverse-Grip Lat Pulldown",
  "Neutral-Grip Lat Pulldown",
  "Pull-Up",
  "Chin-Up",
  "Wide-Grip Pull-Up",
  "Commando Pull-Up",
  "Lat Pullover",
  "Straight-Arm Pulldown",
  "Good Morning",
  "Hyperextension",
  "Back Extension",
  "Reverse Hyperextension",
  "Superman Exercise",

  // Shoulder Exercises
  "Overhead Press",
  "Standing Military Press",
  "Seated Military Press",
  "Dumbbell Shoulder Press",
  "Arnold Press",
  "Push Press",
  "Z Press",
  "Lateral Raise",
  "Front Raise",
  "Rear Delt Fly",
  "Face Pull",
  "Cable Lateral Raise",
  "Cable Front Raise",
  "Cable Rear Delt Fly",
  "Shrug",
  "Cable Shrug",
  "Barbell Shrug",
  "Dumbbell Shrug",
  "Upright Row",
  "Snatch-Grip Upright Row",
  "Cuban Press",
  "Scaption",
  "Trap-3 Raise",

  // Arm Exercises (Biceps)
  "Barbell Curl",
  "Dumbbell Curl",
  "Hammer Curl",
  "Preacher Curl",
  "Spider Curl",
  "Concentration Curl",
  "Cable Curl",
  "EZ-Bar Curl",
  "Zottman Curl",
  "Reverse Curl",
  "Incline Dumbbell Curl",
  "Drag Curl",
  "Cross-Body Hammer Curl",
  "Cable Rope Curl",
  "Bayesian Curl",
  "Barbell Cheat Curl",
  "21s Curl",

  // Arm Exercises (Triceps)
  "Tricep Pushdown",
  "Overhead Tricep Extension",
  "Tricep Dip",
  "Close-Grip Bench Press",
  "Skullcrusher",
  "Tricep Kickback",
  "Rope Pushdown",
  "Single-Arm Cable Pushdown",
  "Lying Tricep Extension",
  "Seated Tricep Press",
  "Dumbbell Skullcrusher",
  "Tate Press",
  "Reverse Grip Tricep Pushdown",
  "Cable Overhead Tricep Extension",
  "Bench Dips",
  "Machine Tricep Extension",

  // Arm Exercises (Forearms)
  "Wrist Curl",
  "Reverse Wrist Curl",
  "Hammer Curl",
  "Zottman Curl",
  "Behind-the-Back Wrist Curl",
  "Farmers Walk",
  "Plate Pinch",
  "Wrist Roller",
  "Towel Pull-Up",
  "Dead Hang",
  "Reverse Barbell Curl",
  "Reverse Grip Wrist Curl",

  // Leg Exercises
  "Squat",
  "Front Squat",
  "Box Squat",
  "Bulgarian Split Squat",
  "Hack Squat",
  "Overhead Squat",
  "Zercher Squat",
  "Jefferson Squat",
  "Leg Press",
  "Lunge",
  "Walking Lunge",
  "Reverse Lunge",
  "Curtsy Lunge",
  "Side Lunge",
  "Pistol Squat",
  "Step-Up",
  "Leg Extension",
  "Leg Curl",
  "Romanian Deadlift",
  "Good Morning",
  "Glute Bridge",
  "Hip Thrust",
  "Sumo Deadlift",
  "Single-Leg Deadlift",
  "Calf Raise",
  "Standing Calf Raise",
  "Seated Calf Raise",
  "Donkey Calf Raise",
  "Sissy Squat",
  "Glute Ham Raise",
  "Cable Pull-Through",
  "Belt Squat",

  // Core Exercises
  "Crunch",
  "Leg Raise",
  "Hanging Leg Raise",
  "Plank",
  "Side Plank",
  "Russian Twist",
  "Bicycle Crunch",
  "Mountain Climber",
  "Flutter Kick",
  "V-Up",
  "Toe Touch",
  "Cable Crunch",
  "Ab Rollout",
  "Dead Bug",
  "Dragon Flag",
  "Windshield Wipers",
  "L-Sit",
  "Side Bend",
  "Cable Woodchopper",
  "Hanging Knee Raise",
  "Medicine Ball Slam",
  "Stomach Vacuum",
  "Standing Cable Crunch",
  "Weighted Sit-Up",
  "Reverse Crunch",
  "Jackknife Sit-Up",
  "Oblique Crunch",
  "Cable Twist",
  "Hollow Body Hold",

  // Full-Body Exercises
  "Clean and Press",
  "Snatch",
  "Kettlebell Swing",
  "Burpee",
  "Thruster",
  "Turkish Get-Up",
  "Man Maker",
  "Bear Complex",
  "Bear Crawl",
  "Medicine Ball Slam",
  "Sandbag Clean",
  "Dumbbell Clean and Press",
  "Power Snatch",
  "Wall Ball",
  "Box Jump",
  "Sled Push",
  "Sled Pull",
  "Battle Ropes",
  "Farmer’s Walk",
  "Carry Variations (Zercher, Overhead)",

  // Cardio Exercises
  "Running",
  "Sprinting",
  "Cycling",
  "Rowing",
  "Jump Rope",
  "Boxing",
  "Shadow Boxing",
  "Swimming",
  "Elliptical",
  "Stair Climber",
  "Battle Ropes",
  "High Knees",
  "Jumping Jacks",
  "Mountain Climbers",
  "Burpees",
  "Rowing Machine",
  "Air Bike",
  "Treadmill Sprints",
  "Incline Treadmill Walk",
  "Box Jump Burpee",
  "Speed Skaters",

  // Olympic Lifts
  "Clean",
  "Clean and Jerk",
  "Snatch",
  "Power Clean",
  "Power Snatch",
  "Split Jerk",
  "Hang Clean",
  "Hang Snatch",
  "Push Jerk",
  "High Pull",
  "Hang High Pull",
  "Snatch Balance",
  "Overhead Squat",

  // Machine Exercises
  "Leg Press Machine",
  "Smith Machine Squat",
  "Smith Machine Bench Press",
  "Smith Machine Shoulder Press",
  "Lat Pulldown Machine",
  "Seated Row Machine",
  "Leg Curl Machine",
  "Leg Extension Machine",
  "Chest Press Machine",
  "Shoulder Press Machine",
  "Pec Deck Machine",
  "Cable Crossover Machine",
  "Tricep Extension Machine",
  "Biceps Curl Machine",
  "Hack Squat Machine",
  "Calf Raise Machine",
  "Dip Machine",
  "Ab Crunch Machine",
  "Glute Ham Developer",
  "Assisted Pull-Up Machine",

  // Stretching & Mobility Exercises
  "Foam Rolling",
  "Hamstring Stretch",
  "Quad Stretch",
  "Hip Flexor Stretch",
  "Chest Stretch",
  "Shoulder Stretch",
  "Triceps Stretch",
  "Lunge Stretch",
  "Cat-Cow Stretch",
  "Child’s Pose",
  "Hip Circle",
  "Shoulder Circle",
  "Ankle Circle",
  "Neck Stretch",
  "Cobra Stretch",
  "Seated Forward Fold",
  "Hip Internal Rotation Stretch",
  "Pigeon Pose",
  "Thread the Needle",
  "Wall Angels",
  "Scapular Push-Up",
  "Scapular Retraction",
  "Thoracic Spine Rotation",
  "Wrist Flexor Stretch",
  "Wrist Extensor Stretch",
  "Calf Stretch",
  "Spinal Twist",
  "Lat Stretch",
  "Side Bend Stretch",
];

export default workoutOptions;
